// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh7TUsuFqQy6NpJ_Kky6-yTl9Irf4y6jE',
    appId: '1:286448192116:web:5bf7542454eab5297f9f21',
    messagingSenderId: '286448192116',
    projectId: 'fasum-app-75876',
    authDomain: 'fasum-app-75876.firebaseapp.com',
    storageBucket: 'fasum-app-75876.firebasestorage.app',
    measurementId: 'G-J5YWY11F08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt6W8-HY_td99p_wLstg0QplIRs4uMcxU',
    appId: '1:286448192116:android:466a4150342ea6e77f9f21',
    messagingSenderId: '286448192116',
    projectId: 'fasum-app-75876',
    storageBucket: 'fasum-app-75876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJMsY1XjqV0OiI2I8nL8rXpIiRrF51Ug',
    appId: '1:286448192116:ios:5c5e892f2451ba517f9f21',
    messagingSenderId: '286448192116',
    projectId: 'fasum-app-75876',
    storageBucket: 'fasum-app-75876.firebasestorage.app',
    iosClientId: '286448192116-u6uieqoje9097i9fanu54blh3sf38fop.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJMsY1XjqV0OiI2I8nL8rXpIiRrF51Ug',
    appId: '1:286448192116:ios:5c5e892f2451ba517f9f21',
    messagingSenderId: '286448192116',
    projectId: 'fasum-app-75876',
    storageBucket: 'fasum-app-75876.firebasestorage.app',
    iosClientId: '286448192116-u6uieqoje9097i9fanu54blh3sf38fop.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh7TUsuFqQy6NpJ_Kky6-yTl9Irf4y6jE',
    appId: '1:286448192116:web:11248f0ed9abf9747f9f21',
    messagingSenderId: '286448192116',
    projectId: 'fasum-app-75876',
    authDomain: 'fasum-app-75876.firebaseapp.com',
    storageBucket: 'fasum-app-75876.firebasestorage.app',
    measurementId: 'G-1LF5DPGYQQ',
  );
}
