// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_xjI4bCyszIHHWorBztIVDdjPBmO7nE',
    appId: '1:527195785995:web:19aa3931b0ce83351e700e',
    messagingSenderId: '527195785995',
    projectId: 'alex-app-88c6b',
    authDomain: 'alex-app-88c6b.firebaseapp.com',
    databaseURL: 'https://alex-app-88c6b-default-rtdb.firebaseio.com',
    storageBucket: 'alex-app-88c6b.firebasestorage.app',
    measurementId: 'G-JTF6ELMEE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmfLqcADHuYhUO8HroZbCjR9FZHMuv5aY',
    appId: '1:527195785995:android:bbc0b9dc13b6922f1e700e',
    messagingSenderId: '527195785995',
    projectId: 'alex-app-88c6b',
    databaseURL: 'https://alex-app-88c6b-default-rtdb.firebaseio.com',
    storageBucket: 'alex-app-88c6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06yRneliVZ7gKNNg7Jm-5AfBepKKUOzs',
    appId: '1:527195785995:ios:99d81e6d549915241e700e',
    messagingSenderId: '527195785995',
    projectId: 'alex-app-88c6b',
    databaseURL: 'https://alex-app-88c6b-default-rtdb.firebaseio.com',
    storageBucket: 'alex-app-88c6b.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06yRneliVZ7gKNNg7Jm-5AfBepKKUOzs',
    appId: '1:527195785995:ios:99d81e6d549915241e700e',
    messagingSenderId: '527195785995',
    projectId: 'alex-app-88c6b',
    databaseURL: 'https://alex-app-88c6b-default-rtdb.firebaseio.com',
    storageBucket: 'alex-app-88c6b.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw_xjI4bCyszIHHWorBztIVDdjPBmO7nE',
    appId: '1:527195785995:web:60f51f2e8dc893041e700e',
    messagingSenderId: '527195785995',
    projectId: 'alex-app-88c6b',
    authDomain: 'alex-app-88c6b.firebaseapp.com',
    databaseURL: 'https://alex-app-88c6b-default-rtdb.firebaseio.com',
    storageBucket: 'alex-app-88c6b.firebasestorage.app',
    measurementId: 'G-THY7W5V2VE',
  );
}
